version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow

  webserver:
    image: apache/airflow:2.8.1-python3.10
    restart: always
    depends_on:
      - postgres
    environment:
      CMEMS_USERNAME: khanin.cht@gmail.com
      CMEMS_PASSWORD: your_actual_password_here
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./csv:/opt/airflow/csv
      - ./db:/opt/airflow/db
    ports:
      - "8181:8080"
    command: bash -c "pip install -r /requirements.txt && airflow webserver"
    networks:
      - airflow

  scheduler:
    image: apache/airflow:2.8.1-python3.10
    restart: always
    depends_on:
      - webserver
    environment:
      CMEMS_USERNAME: khanin.cht@gmail.com
      CMEMS_PASSWORD: your_actual_password_here
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./csv:/opt/airflow/csv
      - ./db:/opt/airflow/db
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"
    networks:
      - airflow

  airflow-init:
    image: apache/airflow:2.8.1-python3.10
    depends_on:
      - postgres
    environment:
      CMEMS_USERNAME: khanin.cht@gmail.com
      CMEMS_PASSWORD: Nincht9077
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./csv:/opt/airflow/csv
      - ./db:/opt/airflow/db
    entrypoint: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com"
    networks:
      - airflow

volumes:
  postgres-db-volume:

networks:
  airflow:
