version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow

  webserver:
    image: apache/airflow:2.8.1-python3.10
    restart: always
    depends_on:
      - postgres
    environment:
        CMEMS_USERNAME: ${CMEMS_USERNAME}
        CMEMS_PASSWORD: ${CMEMS_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt   # ✅ เพิ่มบรรทัดนี้
    ports:
      - "8080:8080"
    command: bash -c "pip install -r /requirements.txt && airflow webserver"  # ✅ แก้ command
    networks:
      - airflow


  scheduler:
    image: apache/airflow:2.8.1-python3.10
    restart: always
    depends_on:
      - webserver
    environment:
        CMEMS_USERNAME: ${CMEMS_USERNAME}
        CMEMS_PASSWORD: ${CMEMS_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt   # ✅ เพิ่มบรรทัดนี้
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"  # ✅ แก้ command
    networks:
      - airflow


volumes:
  postgres-db-volume:

networks:
  airflow:
